### ISSUE TITLE
jsdoc 参数检查疑似误报

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/fecs#101]
```js
    /**
     * 根据URL字符串生成请求发送器
     *
     * 传入一个字符串时，只返回一个发送器函数；传入数组或对象时，递归；传入函数时
     *
     * @param {string|Array.<string>|Object.<string, string>|function} url 请求路径或多个请求路径的集合，或是取值函数
     * @param {function(string):boolean} isRequester 判断是否是需要生成请求发送器的路径
     * @return {function|Array.<function>|Object.<string, function>} 将对应的路径转换为发送器后返回
     */
```

第一个`param`和`return`报了以下错误：
![image](https://cloud.githubusercontent.com/assets/2787987/8956793/d170e22e-362b-11e5-9ff2-542386b74025.png)

当`function`改成`Function`时，警报消除，但是第二个`param`一直没有出现警报，是否与`|`表达式有关？

**Comment by chriswong** [comment]
目前规范是这么定义的：
https://github.com/ecomfe/spec/blob/master/javascript-style-guide.md#强制-对于基本类型-string-number-boolean首字母必须小写

**Comment by chestnutchen** [comment]
ok，明白了
