### ISSUE TITLE
Jquery ajax data 参数属性带下划线造成代码不符合规范

### ISSUE THREAD

**Issue by iyaozhen** [ecomfe/fecs#103]
如图：
![image](https://cloud.githubusercontent.com/assets/4395553/9060177/e3cce9d8-3ae3-11e5-94fb-1ba543229dad.png)

这个怎么解决？自己拼 query url 太麻烦了。

**Comment by Justineo** [comment]
[Wiki](https://github.com/ecomfe/fecs/wiki/HowToFix#js-rule030-%E5%BC%BA%E5%88%B6-%E7%B1%BB%E7%9A%84-%E6%96%B9%E6%B3%95--%E5%B1%9E%E6%80%A7-%E4%BD%BF%E7%94%A8-camel%E5%91%BD%E5%90%8D%E6%B3%95) 里有说明。

**Comment by iyaozhen** [comment]
嗯嗯，看到了。谢谢
实在抱歉，当时 wiki 没仔细看完。
