### ISSUE TITLE
fecs format大括号之后多了一空行

### ISSUE THREAD

**Issue by hushicai** [ecomfe/fecs#106]
如下所示 

![1](https://cloud.githubusercontent.com/assets/1249423/9354092/0a810b50-46a0-11e5-8218-dcc9d0bb13b2.gif)

**Comment by ishowshao** [comment]
竟然还有这个问题😅我来看看

发自我的 iPhone

**Comment by xuexb** [comment]
这是文件末尾加空行规则吧

**Comment by chriswong** [comment]
是 esformatter 的配置问题
