### ISSUE TITLE
收集一下 fecs-format 之后未修复的 warning/error 或 bug

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#108]
RT.

**Comment by hushicai** [comment]
本来是ok的，格式化后反而报错：

![image](https://cloud.githubusercontent.com/assets/1249423/9461308/418dd656-4b40-11e5-9d53-a1333af4c496.png)

**Comment by chriswong** [comment]
超 120 字符？

**Comment by hushicai** [comment]
else if 格式化貌似也有问题，本来是这样：

![image](https://cloud.githubusercontent.com/assets/1249423/9461342/96f2500e-4b40-11e5-9023-7bd4b6982d2c.png)

格式化后：

![image](https://cloud.githubusercontent.com/assets/1249423/9461351/a7484936-4b40-11e5-992f-bb1f8914526a.png)

**Comment by hushicai** [comment]
注释后面的空格没去掉。

![image](https://cloud.githubusercontent.com/assets/1249423/9485584/35693d62-4bee-11e5-8537-90f73141c2d7.png)

**Comment by hushicai** [comment]
warning: no-else-return

![image](https://cloud.githubusercontent.com/assets/1249423/9489285/85399c8c-4c12-11e5-806a-69826022cd65.png)

**Comment by hushicai** [comment]
guard-for-in:

![image](https://cloud.githubusercontent.com/assets/1249423/9541003/b08099b0-4d96-11e5-9cda-5bb30259308b.png)

没有自动添加上hasOwnProperty.

**Comment by nighca** [comment]
> 没有自动添加上hasOwnProperty.

这个会改变代码的语义吧，自动加有风险。

**Comment by xuexb** [comment]
`let a`会被格式化成`leta`
