### ISSUE TITLE
HTML 检测能否对特定的类名设置白名单

### ISSUE THREAD

**Issue by 599316527** [ecomfe/fecs#110]
某些特定的类名如 `ec_wise_utouch ` 或 `container_l` 因为依赖其他环境而无法修改得符合规范，能否设置忽略这些类名？

**Comment by nighca** [comment]
目前还不支持忽略指定的 class 列表。上面这个情况可以考虑配置禁用 `lowercase-class-with-hyphen` 这条规则。
