### ISSUE TITLE
写了个atom 编辑器插件，能否readme超链接过去？

### ISSUE THREAD

**Issue by 8427003** [ecomfe/fecs#122]
https://github.com/8427003/atom-fecs

**Comment by firede** [comment]
建议直接提 Pull Request

**Comment by 8427003** [comment]
这是个独立插件，不属于fecs核心代码。@firede

**Comment by firede** [comment]
嗯嗯，我是说直接在 fecs 的 README.md 里加你的链接，然后发个 PR 即可

**Comment by chriswong** [comment]
readme 和 wiki 都加好了，官网等下个版本
