### ISSUE TITLE
关于html中提示不能使用style tag的疑问

### ISSUE THREAD

**Issue by Hellowor1d** [ecomfe/fecs#124]
在首页Demo中，html的提示中有这样一行： 
     WARN → line 8, col 5: Style tag can not be used.
然而按照提示修改其他各处之后，最后修改line8的 style 为 s 竟然提示
    fecs INFO Congratulations! Everything is OK!
其中的  s  是随意实验的，然而提示无错，对此表示不太理解！

**Comment by chriswong** [comment]
不允许使用 <style> 属于建议级别，tagName 改成 s 之后并没有针对此条的规则，因此不报错是理所当然的
