### ISSUE TITLE
windows环境安装依赖报错

### ISSUE THREAD

**Issue by xuexb** [ecomfe/fecs#150]
昨天在 [appveyor](https://ci.appveyor.com/project/xuexb/key-cache) 上跑测试时有依赖`fecs`，发现在node 0.12, 4.x, 5.x版本均报错，之前是没有问题的，本以为是我环境问题，于是在本地虚拟机windows10中`clone fecs`，并安装依赖也报相同的错，如图：

![image](https://cloud.githubusercontent.com/assets/3872051/13065409/13960882-d497-11e5-9276-9b68537594ac.png)

**Comment by chriswong** [comment]
看起来是 gonzales-pe@3.2.6 的问题，你尝试试安装 gonzales-pe@3.2.1 看看

**Comment by xuexb** [comment]
@chriswong 刚试了下， gonzales-pe@3.2.1 可以安装，3.2.6不行，如图：

<a href="https://cloud.githubusercontent.com/assets/3872051/13066481/51ff467e-d4a1-11e5-97ed-8ea16b1887af.png">
<img src="https://cloud.githubusercontent.com/assets/3872051/13066481/51ff467e-d4a1-11e5-97ed-8ea16b1887af.png" width=300>
</a>

**Comment by chriswong** [comment]
https://github.com/tonyganch/gonzales-pe/issues/149

**Comment by xuexb** [comment]
额。。。没看懂，他这是不修复了么。。。

**Comment by chriswong** [comment]
修复 mac 下的问题，又带出 windows 下的问题，如果你的环境可控，可以指定安装 3.2.1 版本，否则我发个锁定 3.2.1 的版本。
