### ISSUE TITLE
同级PropertyName中有保留字时，MethodDefinition 规则应当忽略

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/fecs#151]
同级PropertyName中有保留字时，再强制应用 MethodDefinition 规则会搞出这样的代码：

```js
{
  'default': 'a',
  'test'() {}
}
```
太丑

建议此时应当忽略 MethodDefinition 规则，可以使用 PropertyName: FunctionExpression 的写法，即：

```js

{
  'defalut': 'a',
  'test': function () {}
}

```

可复现版本：0.6.2

**Comment by Justineo** [comment]
我们现在不是不强制所有 key 同步加引号了么？

**Comment by chriswong** [comment]
> 我们现在不是不强制所有 key 同步加引号了么？

现在是 warning，他处女座

**Comment by otakustay** [comment]
嗯，感觉method shorthand应该独立出来，不作为peoperty key应用这类规则

**Comment by chriswong** [comment]
现在是加了一个配置，默认允许忽略 spread、computed 和 method：

https://github.com/ecomfe/fecs/commit/cbad9eec401b526c9063a1f22409f2c1c75f7ca7#diff-98b428fb13906514c9253012bed738e3R51
