### ISSUE TITLE
方正字体显示问题~！？

### ISSUE THREAD

**Issue by dotku** [ecomfe/fecs#152]
为什么用了 font-face 还是这样？！

![显示不清楚](http://pasteio.com/m9cbbe19dc724335125405d9b37dc5922)

我的电脑是 Windows 10

**Comment by cgzero** [comment]
请问具体浏览器是？ie10上我看了默认浏览器和chrome没问题，倒是xp下的ie8会这样

**Comment by dotku** [comment]
@cgzero Windows 10, 360 浏览器 8.1 (我也测试了一下 Chrome 浏览器，确实没有问题... 360 就悲剧了...)
