### ISSUE TITLE
规则`fecs-valid-jsdoc`需要支持函数参数解构

### ISSUE THREAD

**Issue by liuxuanzy** [ecomfe/fecs#153]
问题代码如下：

``` javascript
   /**
     * 构造函数
     *
     * @param {string} account 账号
     * @param {string} password 密码
     */
    constructor({account, password}) {
        this.username = account;
        this.token = password;
    }
```

fecs会报：
Expected JSDoc for "ObjectPattern" but found "account". (fecs-valid-jsdoc)

**Comment by nighca** [comment]
如果解构参数的注释这么写的话，就没法区分以下两种情况了：

    // 一个 Object 参数
    constructor({account, password}) {
        this.username = account;
        this.token = password;
    }

   // 两个 string 参数
    constructor(account, password) {
        this.username = account;
        this.token = password;
    }

这里 fecs 对注释的要求是按一个普通的 Object 参数的方式写，我觉得是合理的。

**Comment by liuxuanzy** [comment]
但是这样没有办法知道对应的Object是什么，因为这个object没有名字

**Comment by liuxuanzy** [comment]
另外目前Web Storm的办法是两种写一样的注释

**Comment by chriswong** [comment]
如果没有看代码，这种注释的 API 会误导为传两个参数

**Comment by nighca** [comment]
https://github.com/jsdoc3/jsdoc/issues/987

**Comment by chriswong** [comment]
fecs@0.7.0-beta.1 中已经兼容此种注释方式

https://github.com/ecomfe/fecs/blob/develop/test/lib/js/rules/valid-jsdoc.spec.js#L607
