### ISSUE TITLE
windows版本 sublime

### ISSUE THREAD

**Issue by catjam** [ecomfe/fecs#154]
配置之后，每次保存会弹框，而且时间比较长，有什么好的解决方法，或者调成异步的
"node_bin": "D:/Program Files/nodejs/node.exe"

**Comment by liuliangsir** [comment]
window submlime text 3 fecs插件感觉没有效果呀，然后关闭弹框后，会报错误
![image](https://cloud.githubusercontent.com/assets/8049878/13723809/10a942ba-e8ab-11e5-8115-248af45b7f1f.png)
如何解决

**Comment by xuexb** [comment]
是想基于`fecs`在sublime里检查\格式化代码吗？我自己写了个，大概的思路是：全局使用`npm`安装`fecs`，然后配置sublime里使用xxx快捷键时调用`node`调执行`fecs filepath`，以让全局的`fecs`去操作文件，比如：[https://github.com/xuexb/sublime-fecs](https://github.com/xuexb/sublime-fecs)

**Comment by liuliangsir** [comment]
我刚体验下，效果还不错，已推荐给其他朋友@xuexb

**Comment by chriswong** [comment]
如上，windows 下建议使用 https://github.com/xuexb/sublime-fecs，issue 关闭。
