### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by yumenglong** [ecomfe/fecs#161]
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by Justineo** [comment]
你的图片没有上传成功。

**Comment by yumenglong** [comment]
恩，是的 ，我还是贴上报错的代码吧   
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.  @Justineo

**Comment by chriswong** [comment]
这个只是提示这个模块太老，未来可能在新的 node 上无法使用

**Comment by yumenglong** [comment]
这个不就是说更新到4.0.0版本就好了嘛？我看我的版本是4.1.3啊，不知为啥还提示

**Comment by chriswong** [comment]
不是你的问题，是因为现在 fecs 依赖的某个模块中依赖的 graceful-fs 版本太老导致的警报，目前并不影响使用，我会更新依赖模块的版本测试没问题后发布新版 fecs

**Comment by yumenglong** [comment]
哦  好的

**Comment by chriswong** [comment]
试一下 fecs@beta 版

**Comment by yumenglong** [comment]
测试版可以安装成功，但是JSCS Package的路径应该是哪个？是这个“ C:\Users\cp\AppData\Roaming\npm\node_modules\fecs
”吗？     @chriswong

**Comment by chriswong** [comment]
https://github.com/leeight/Baidu-FE-Code-Style

如果是用了这个插件的话，需要写这个插件的路径

**Comment by yumenglong** [comment]
可是这个插件不是已经安装到本地了吗？我在本地找不到Baidu-FE-Code-Style这个目录啊

**Comment by chriswong** [comment]
已经安装到本地，然后又找不到它的目录？如果是通过 Sublime 安装的，应该在它的插件目录下

我上面是发插件的地址让你看说明。。。。并不是让你把网址当路径贴 JSCS Package 的路径里

**Comment by yumenglong** [comment]
你发的这个网址“https://github.com/leeight/Baidu-FE-Code-Style”，我之前就看过了，我就是按照里面webstorm安装的步骤做的，我就是想问JSCS Package的路径改咋配！

**Comment by chriswong** [comment]
https://github.com/leeight/Baidu-FE-Code-Style#安装-1

这里不是写得很清楚的吗？
