### ISSUE TITLE
在.fecsrc中配置no-var无效和配置完files后再配置.fecsignore无效

### ISSUE THREAD

**Issue by DreamTear** [ecomfe/fecs#165]
在.fecsrc中配置：
`{
    "files": [
        "static"
    ],
    "eslint": {
        "env": {
            "node": false
        },
        "rules": {
            "no-var": 0
        }
    }
}`
.fecsignore配置：
`static/lib`
配置后代码检查后还是会报no-var的错，另外就是还是检查了static/lib下的内容，
但是在文件中添加/* eslint-disable no-var */是可以的，我的目的主要是去除es6的语法的代码检测。

**Comment by chriswong** [comment]
第一个问题，是因为对于 es-next 专用的规则，会在代码检测是否为 es-next 代码时动态打开或关闭，这个操作的优化级比本地配置要高，而比文件内的 inline comment 配置低。因此可以通过在 `env` 中设置 es6 为 false 来避免打开规则，或者使用 `/* eslint-disable no-var */` 来关闭。

第二个问题是为了 hack 一种特殊情况，在 .fecsrcignore 中添加了 static/lib，但是又想通过 fecs static/lib 来检查时，期望继续进行检查。不过针对在 files 中指定路径的情况，可以不提高优先级，保持 ignore 配置更高的优先级即可，下个版本会作调整。
