### ISSUE TITLE
能否把@file和@author的jsdoc规则独立一个Rule

### ISSUE THREAD

**Issue by otakustay** [ecomfe/fecs#170]
个人项目偷懒不想写这些，但是还是想检查方法等的jsdoc

**Comment by chriswong** [comment]
刚提交的 @beta 版有

**Comment by chriswong** [comment]
https://github.com/ecomfe/fecs/blob/develop/lib/js/rules/valid-jsdoc.js#L737-L745
https://github.com/ecomfe/fecs/blob/develop/lib%2Fjs%2Feslint.yml#L30-L59

**Comment by otakustay** [comment]
具体的用法是不是：

```
{
  "eslint":
    "rules":
      "fecs-valid-jsdoc": {
        "requireAuthor": false
      }
   }
}
```

这样？

**Comment by chriswong** [comment]
对

**Comment by otakustay** [comment]
good
