### ISSUE TITLE
安装时出现错误

### ISSUE THREAD

**Issue by tedpenk** [ecomfe/fecs#173]
安装命令：
npm config set registry http://registry.npm.baidu.com
npm install fecs --save

错误截图：
![image](https://cloud.githubusercontent.com/assets/7235487/14845069/76edf712-0c8e-11e6-8e7f-b31800e6e03f.png)
请问如何解决？

操作系统：Win7
![image](https://cloud.githubusercontent.com/assets/7235487/14845161/0c75e61e-0c8f-11e6-9a3b-a205537f5234.png)
![image](https://cloud.githubusercontent.com/assets/7235487/14845169/1466f58e-0c8f-11e6-8d5f-a5e7038223af.png)

**Comment by chriswong** [comment]
加了 shrinkwrap 来锁定版本，你试试 fecs@0.7.4

**Comment by chriswong** [comment]
http://registry.npm.baidu.com 上的 fecs 版本是不是太老了，这个问题在 fecs@0.6.5 之后就修复了的

**Comment by tedpenk** [comment]
可以了，谢谢！
