### ISSUE TITLE
ESLint wiki中【默认规则】链接出错

### ISSUE THREAD

**Issue by xuexb** [ecomfe/fecs#186]
如题，[wiki/ESLint](https://github.com/ecomfe/fecs/wiki/ESLint) 中的

> ## 默认规则
> 
> 2\. https://github.com/ecomfe/fecs/blob/master/lib/js/eslint.json

的链接404了

**Comment by xuexb** [comment]
同样 wiki/HTMLCS 这里面的`json`配置文件也404了，应该是转`yml`了

**Comment by nighca** [comment]
已修正
