### ISSUE TITLE
[建议] 对数组进行连接操作时，使用数组展开语法

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#190]
https://github.com/ecomfe/spec/blob/master/es-next-style-guide.md#建议-对数组进行连接操作时使用数组展开语法

> 解释：
> 
> 用数组展开代替 `concat` 方法，数组展开对 `Iterable` 有更好的兼容性。
> 
> 示例：
> 
> ```javascript
> // good
> let foo = [...foo, newValue];
> let bar = [...bar, ...newValues];
> 
> // bad
> let foo = foo.concat(newValue);
> let bar = bar.concat(newValues);
> ```

**Comment by PeterPanZH** [comment]
使用Buffer.concat时会误报
