### ISSUE TITLE
.fecsrc[fecs-esnext-ext] 不能覆盖警告信息

### ISSUE THREAD

**Issue by mudio** [ecomfe/fecs#207]
#184 这个改动导致.fecsrc[fecs-esnext-ext] 不能覆盖警告信息这是预期的吗？

**Comment by chriswong** [comment]
1. 只有 0 1 2，3 不是合法的数值
2. 针对 esnext 的规则需要根据  ast 识别为 esnext 动态打开或关闭，所以不允许自己关闭，目前是符合预期的
