### ISSUE TITLE
[建议] 使用解构减少中间变量

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#208]
https://github.com/ecomfe/spec/blob/master/es-next-style-guide.md#建议-使用解构减少中间变量

> 解释：
> 
> 常见场景如变量值交换，可能产生中间变量。这种场景推荐使用解构。
> 
> 示例：
> 
> ```javascript
> // good
> [x, y] = [y, x];
> 
> // bad
> let temp = x;
> x = y;
> y = temp;
> ```

**Comment by treelite** [comment]
大佛～ `0.7.25` 版本，针对这段代码：

```js
function test(query) {
    let [name, repo] = query.split('/');
    return {name, repo};
}
```

会在第一行函数定义那里提示 “[建议] 使用解构减少中间变量。”，错误指向函数参数`query`，求解～～
