### ISSUE TITLE
fecs工具可以只查改动吗？

### ISSUE THREAD

**Issue by yuyouwen** [ecomfe/fecs#209]
RT～

**Comment by chriswong** [comment]
这个不是 fecs 的能力范围，是 [kudo](/ecomfe/kudo) 的

**Comment by chriswong** [comment]
确切的说是 eagle 已经有这个功能，kudo 是查某人在某个时间段的代码的规范符合率

fecs 有提供 api，可以只显示指定行、范围的代码的规范检查结果
