### ISSUE TITLE
安装失败 sudo npm install fecs -g

### ISSUE THREAD

**Issue by ronnyKJ** [ecomfe/fecs#220]
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/baidu/.nvm/versions/node/v4.1.2/bin/node" "/Users/baidu/.nvm/versions/node/v4.1.2/bin/npm" "install" "fecs" "-g"
npm ERR! node v4.1.2
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: html-code-gen@stable
npm ERR! Valid install targets:
npm ERR! 0.3.7, 0.3.6, 0.3.5, 0.3.4, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.2, 0.2.1, 0.2.0, 0.1.0, 0.0.1
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/baidu/百度云同步盘/MacFiles/VirtualBoxShare/MAMP/goodcoder/npm-debug.log

**Comment by nighca** [comment]
这个是用了非官方源吧，找不到 `stable` 这个 tag，换成官方源 `https://registry.npmjs.org/` 应该就可以了。

@chriswong 镜像源似乎经常出现这个问题，我们要不要还是把 `stable` 换成指定版本号？

**Comment by chriswong** [comment]
这是淘宝源的 bug，应该推动他们解决

**Comment by nighca** [comment]
印象中百度内部源也有这个问题，不过不太确定

**Comment by chriswong** [comment]
> 印象中百度内部源也有这个问题，不过不太确定

内部源归根结底还是淘宝源...

**Comment by chriswong** [comment]
@ronnyKJ 已经反馈给 cnpm 处理，建议重试一下
