### ISSUE TITLE
fecs-valid-var-jsdoc会不会过于严格

### ISSUE THREAD

**Issue by otakustay** [ecomfe/fecs#223]
看上去任何const声明都会被要求写注释，我一个类用于私有字段可能就几十个Symbol的const，真的有必要一个一个都把注释写上么……

**Comment by otakustay** [comment]
版本0.8.3-beta.2

**Comment by chriswong** [comment]
调整一下要求：

+ 仅当用 **const** 定义，并且有 **@const** 的 jsdoc，此时要求 `变量命名` 符合常量的要求。
+ 仅当用 **const** 定义，变量命名符合常量的要求，并且有 jsdoc 注释 和 description，此时要求必须 jsdoc 注释中必须包含 @const  和 @type。
