### ISSUE TITLE
类的继承及方法相关文档注释规则

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#225]
> [建议] 使用 `@class` 标记类或构造函数。
> [建议] 使用 `@extends` 标记类的继承信息。
> [强制] 使用包装方式扩展类成员时， 必须通过 `@lends` 进行重新指向。
> [强制] 类的属性或方法等成员信息使用 `@public` / `@protected` / `@private` 中的任意一个，指明可访问性。

**Comment by sameenzm** [comment]
那加了这条新规范之后，应该怎么写才对，才能不报错？

**Comment by chriswong** [comment]
参考规范 《类注释》一节：

https://github.com/ecomfe/spec/blob/master/javascript-style-guide.md#247-类注释
