### ISSUE TITLE
.fecsrc 求配置项说明

### ISSUE THREAD

**Issue by 2betop** [ecomfe/fecs#231]
搜了现有 issues 和 wiki 都没看到，只有 FAQ 提了一点点。

**Comment by otakustay** [comment]
fecs用的是3个工具：eslint、csshint、htmlcs，所以`.fecsrc`的结构是这样的：

```json
{
    "files": [...],
    "eslint": {...},
    "csshint": {...},
    "htmlcs": {...}
}
```

其中`files`是一个数组，数组中的每一项是一个[glob表达式](https://github.com/isaacs/node-glob)，用于指定哪些文件用于检测

另外3个对象类型的属性，都参考这3个工具自己的配置就好了

- [csshint的规则列表](https://github.com/CSSLint/csslint/wiki/Rules)
- [htmlcs的规则列表](https://github.com/ecomfe/htmlcs/blob/master/lib/default/htmlcsrc)
- [eslint的配置说明](http://eslint.org/docs/user-guide/configuring)，至少`env`、`globals`、`rules`是有效的，其它的我不太清楚

**Comment by 2betop** [comment]
好的，非常感谢！

**Comment by chriswong** [comment]
WIKI 来了：https://github.com/ecomfe/fecs/wiki/Configuration

另： @otakustay 提供的 csshint 规则有误（csslint），正确参考为：https://github.com/ecomfe/fecs/wiki/CSShint
