### ISSUE TITLE
JS615[建议]使用解构减少中间变量

### ISSUE THREAD

**Issue by sameenzm** [ecomfe/fecs#232]
import {Input, Form} from 'antd'; // Form会报代码检查错误，JS615，建议使用解构减少中间变量
const FormItem = Form.Item;
const createForm = Form.create;
这个建议搞不懂，怎么用解构的写法？

**Comment by otakustay** [comment]
```js
import {Input, Form} from 'antd';
const {Item: FormItem, create: createForm} = Form;
```
