### ISSUE TITLE
[建议] fecs 暂时不开启 fecs-prefer-async-await 规则

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/fecs#233]
建议暂时不开启此规则。

理由是没有任何一个 js 引擎原生支持 async / await，想要使用 async / await 必须进行转义，成本较高。

**Comment by chriswong** [comment]
这个只是 warning 级别，不会影响最后退出的状态码

**Comment by jinzhubaofu** [comment]
warning 会引导 or 压迫同学们去解决啊，强迫症表示不接受有 warning。

**Comment by chriswong** [comment]
你本地关闭不也一样？本地看不到，提交 Cooder/iCode 也不会看到
