### ISSUE TITLE
import前有use strict时会报错

### ISSUE THREAD

**Issue by PeterPanZH** [ecomfe/fecs#234]
当`import`前面有`'use strict';`时会报
> JS2 | [RULE] [强制] 所有 `import` 语句写在模块开始处。

虽然说ES6 module中不用写`'use strict';`也会默认启用strict mode，但是加上也不能算错，而且已经习惯加上了~

**Comment by Justineo** [comment]
编码规范想避免的就是这种可能的不一致（有人写有人不写）？不能算错&习惯加上不能作为理由吧，有很多人也习惯了两空格、不加分号。

**Comment by PeterPanZH** [comment]
那么应该增加 ES6 module 不能使用 use strict directive，而不是报import必须写在开头。我没有说这条规则有问题~

**Comment by Justineo** [comment]
恩，单独搞一条感觉比较好。

**Comment by chriswong** [comment]
这个检查在 7.10 的 0.8.3 版本已经忽略 use strict，规范调整请稳步 spec repo。
