### ISSUE TITLE
如何忽略WARN级别的提醒？

### ISSUE THREAD

**Issue by kazaff** [ecomfe/fecs#236]
如何配置可以忽略html，css，js的warn级别的错误，从而允许提交git？

**Comment by kazaff** [comment]
@ecomfe

**Comment by chriswong** [comment]
你说的 git 是指什么？ github？icode？

**Comment by kazaff** [comment]
@chriswong  fecs提供了git的插件啊~ github只是一个开源平台而已。

**Comment by kazaff** [comment]
解决了，具体方法看这里：
http://blog.kazaff.me/2016/08/17/git%20hook%E5%B8%AE%E4%BD%A0%E7%BB%B4%E6%8A%A4%E5%89%8D%E7%AB%AF%E4%BB%A3%E7%A0%81%E8%A7%84%E8%8C%83/

**Comment by chriswong** [comment]
这个问题跟 fecs-git-hook 的处理有关：https://github.com/cxtom/fecs-git-hooks/blob/master/hooks/pre-commit#L148

fecs 本身的处理是对于 warning 级别的问题是不会影响退出状态码的，这个插件专门判断限制了
