### ISSUE TITLE
[bug] 使用未定义的变量不触发警告

### ISSUE THREAD

**Issue by jinzhubaofu** [ecomfe/fecs#248]
版本: 1.0.0
可复现代码:

```js
export const a = name;
```

**Comment by chriswong** [comment]
浏览器端是有 name 的

**Comment by jinzhubaofu** [comment]
window.name? 用了是个大坑吧。。。感觉至少要加一个警告。。。
那 nodejs 呢。。。

**Comment by otakustay** [comment]
这东西是eslint的`env`参数决定的，如果有`browser`这个环境就会有，你只用Node的话控制下参数就好了

https://github.com/sindresorhus/globals/blob/master/globals.json

**Comment by jinzhubaofu** [comment]
OK 懂了。
