### ISSUE TITLE
如何关闭这个校验规则

### ISSUE THREAD

**Issue by T-baby** [ecomfe/fecs#251]
你好，我想要关闭下面这个校验规则，该如何配置呢？

fecs:104:20HTML004:[强制]'class'必须代表相应模块或部件的内容或功能，不得以样式信息进行命名。[no-meta-css]

**Comment by ielgnaw** [comment]
https://github.com/ecomfe/fecs/wiki/HowToFix

**Comment by T-baby** [comment]
不知道具体配置名啊。。

**Comment by ielgnaw** [comment]
```javascript
/* eslint-disable no-meta-css */
// 这里是需要关闭这条规则的代码段
/* eslint-enable no-meta-css */
