### ISSUE TITLE
可以豁免多个规则吗

### ISSUE THREAD

**Issue by swust-xiaoj** [ecomfe/fecs#256]
`/* eslint-disable xxx, yyy, zzz */`类似于这样

**Comment by ielgnaw** [comment]
可以

```javascript 
function a(){
    var a= 1;
}
```
![image](https://cloud.githubusercontent.com/assets/1153430/20171453/a824a3d0-a76b-11e6-9546-1a0f446410ad.png)
----

```javascript 
/* eslint-disable no-unused-vars, space-before-blocks, space-infix-ops */
function a(){
    var a= 1;
}
```
![image](https://cloud.githubusercontent.com/assets/1153430/20171481/d37439ce-a76b-11e6-8e10-67e6f8893a33.png)
