### ISSUE TITLE
type类型首字母大写问题

### ISSUE THREAD

**Issue by xuexb** [ecomfe/fecs#273]
> JS RULE044 [强制] 对于基本类型 {string}, {number}, {boolean}，首字母必须小写。
> 
> 意思是除了 String/Number/Boolean 类型的首字母小写，其它类型都大写，如：{Array}，{Date}，{Function}，{Object}，{RegExp}。

我看方法参数的类型是正确的, 但变量的类型没有验证, 是正常吗? 代码如:

```js
/**
 * @file test
 * @author test
 */

/**
 * x
 *
 * @param  {object} xxx xxx
 */
function xxoo(xxx) {}

/**
 * test
 *
 * @type {object}
 */
var obj = {};

obj.test = 1;


xxoo();

```

官网demo里结果如:

```
fecs ERROR → line 9, col 2: Use "Object" instead of "object".
```

**Comment by ielgnaw** [comment]
请参见 ecomfe javascript 代码规范

**Comment by ielgnaw** [comment]
请参见 ecomfe javascript 代码规范
[类型定义](https://github.com/ecomfe/spec/blob/master/javascript-style-guide.md#244-类型定义)
