### ISSUE TITLE
方便提供.vue文件的代码检查吗？

### ISSUE THREAD

**Issue by Jaylentse** [ecomfe/fecs#282]
方便提供.vue文件的代码检查吗？

**Comment by otakustay** [comment]
根据 https://github.com/ecomfe/fecs/commit/5aa07e0df5e1baf8bdb90a436193dc9f5c6e738a 这里显示，最新版应该是支持的，如果有BUG的话说明一下怎么复现吧

**Comment by tangciwei** [comment]
请问vue文件咋使用，vue文件里面包含<template>、<script>、<style>三部分，如何格式化？

以下命令都不行：
fecs format xxx.vue 
fecs format xxx.vue --type=js

**Comment by chriswong** [comment]
@tangciwei 目前并不支持直接对 .vue 格式化，单个文件可以这样用：

cat xxx.vue | fecs format -r --type=html > xxx.vue

**Comment by tangciwei** [comment]
调用fecs写了一个

**Comment by iCodeBIT** [comment]
试用了一下，目前对vue文件的检查是只针对script标签做js检查吗？ 好像并没有对template标签做HTML检查和针对style标签做css检查？
