### ISSUE TITLE
cli中使用ckeck filename --ignore, ignore失效

### ISSUE THREAD

**Issue by win7killer** [ecomfe/fecs#296]
cli中，
fecs format [pattern...] [options]
不用pattern的时候，可以忽略文件夹 比如“src/libs”
使用pattern后，libs文件夹下文件无法忽略

**Comment by chriswong** [comment]
pattern 会提高到最高优先级，如果需要忽略，可以在配置文件中使用 files 字段配置 **!** 开头的规则
