### ISSUE TITLE
调用 fecs.check API 在传入文件所在路径以及 stream 的前提下，.fecsrc 和 .fecsignore 不生效

### ISSUE THREAD

**Issue by zoumiaojiang** [ecomfe/fecs#300]
RT

直接上代码：

```
  // 如果 .fecsrc 在 /a/b 下
  function getOptions() {
        return Object.assign(
            {},
            fecs.getOptions(),
            {
                _: [
                    '/a/b/c'
                ],
                reporter: 'baidu'
                level: 0,
                stream: stream
            }
        );
    }

    fecs.check(getOptions(), function (success, json) {
        // ...
    });

```

这种用法 .fecsrc 不会生效。。

**Comment by l5oo00** [comment]
我试了下， `.fecsrc` 是支持的， 但`.fecsignore`貌似不支持。

看了下代码，同时实际测试了下，  貌似只是用的当前目录下的 `.fecsignore` 

不像 `.fecsrc`  那样会依次遍历上级目录？

**Comment by ielgnaw** [comment]
`.fecsrc` 是支持的，这样写 
```js
const fecs = require('fecs');
const path = require('path');
const a = fecs.check({
    _: [path.join(__dirname, './test.js')],
    lookup: true,
    stream: false,
    type: 'js'
}, function (success, errors) {
    console.log(JSON.stringify(errors, null, 4));
});
```
注意 options 传入 `_` 和 `lookup` 

`.fecsignore` 还在看

**Comment by ielgnaw** [comment]
这个看逻辑是这样的
> 看了下代码，同时实际测试了下， 貌似只是用的当前目录下的 .fecsignore

这算是个问题了吧 @chriswong

**Comment by l5oo00** [comment]
刚才看了下， 发现好像  `.fecsignore` 和  `.gitignore` 的语法并不是很一致， 比如：

新建个目录`/path/to/repo`， 目录结构如下：

```bash
├── .fecsignore
├── .gitignore
├── dir1
│   └── index.js
└── index.js
```

两个 ignore 文件内容都是 `*.js`,   git 会把`index.js` 和 `dir1/index.js` 都忽略了， 但运行 fecs 还是会检查 `dir1/index.js` ，应该以哪个为准呢？

**Comment by chriswong** [comment]
.fecsignore 当初设计是在跟 package.json 相同的位置，只配置一次，后来在 .fecsrc 的 files 中也可以配置 ignore 之后，不再推荐使用 .fecsignore
