### ISSUE TITLE
fecs 全局安装失败

### ISSUE THREAD

**Issue by OshotOkill** [ecomfe/fecs#303]
MacOS 10.12.6
node 8.3.0
npm 5.3.0

sudo npm i -g 无法正常安装

<img width="1243" alt="2017-08-16 10 44 05" src="https://user-images.githubusercontent.com/6079112/29345227-e8aebc8a-826f-11e7-9240-96abba42194a.png">

**Comment by jinzhubaofu** [comment]
没有文件 rename 的权限，可能是因为你安装在 /usr/local 下有关。

建议用 nvm 安装 node，或者放到个人目录下保证有 rename 权限
