### ISSUE TITLE
fecs后续会加入react相关文件的检查么？

### ISSUE THREAD

**Issue by anyexinglu** [ecomfe/fecs#307]
如题，比如按照这个React规范（草案）：
https://github.com/ecomfe/spec/blob/master/react-style-guide.md

目前项目需要，一处处去比对较为耗时，也容易遗漏

**Comment by otakustay** [comment]
最新版fecs在fecsrc中的eslint.env中添加react就可以了

-- 
Gray Zhang

在 2017年9月24日 at 下午9:53:49, anyexinglu (notifications@github.com) 写到:
