### ISSUE TITLE
请问是不支持eslint的 extends 字段配置么

### ISSUE THREAD

**Issue by imwtr** [ecomfe/fecs#319]
没有看到生效~

**Comment by otakustay** [comment]
fecs当前用的还是eslint3，所以基本能确定是不支持的

发件人: imwtr <notifications@github.com>
答复: ecomfe/fecs <reply@reply.github.com>
日期: 2018年3月19日 星期一 下午6:34
收件人: ecomfe/fecs <fecs@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [ecomfe/fecs] 请问是不支持eslint的 extends 字段配置么 (#319)


没有看到生效~

―

**Comment by imwtr** [comment]
嗯这样子
