### ISSUE TITLE
Moving away from the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [ecomfe/fecs#327]
`new Buffer(...)` is deprecated and unsafe. Is it possible to update the code base to use `Buffer.from(...)`? The constructor is called in [these places](https://github.com/ecomfe/fecs/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22).

**Comment by Phinome** [comment]
Thanks. i will resolve it soon.

**Comment by Phinome** [comment]
it's work now, i was closed it.
