### ISSUE TITLE
已经按照冒号对齐的代码不通过

### ISSUE THREAD

**Issue by sunweifeng** [ecomfe/fecs#37]
-webkit-animation-duration: .6s;
               animation-duration: .6s;
RULE046--eagle
RULE046-[强制] 带私有前缀的属性由长到短排列，按冒号位置对齐。

**Comment by chriswong** [comment]
源码是这个格式吗？这个格式没有按冒号对齐啊，有个类似的 bug 之前是已经修复过的。 @ielgnaw

**Comment by sunweifeng** [comment]
嗯， 前几次提交都提示这个问题，最近的一次提交这个问题没了，我也没做什么修改，，诡异

**Comment by chriswong** [comment]
大概在 12.26 号升级了 csshint，有包含对这个问题的修复。
