### ISSUE TITLE
无法使用rgba属性

### ISSUE THREAD

**Issue by sunweifeng** [ecomfe/fecs#38]
-webkit-box-shadow: 5px 5px 20px rgba(0, 0, 0, .6);
211	            box-shadow: 5px 5px 20px rgba(0, 0, 0, .6);
RULE029--eagle
RULE029-[强制] RGB颜色值必须使用十六进制记号形式 `#rrggbb`。不允许使用 `rgb()`。

**Comment by chriswong** [comment]
这 bug 是已经修复过的，有可能是 eagle 还未更新版本。 @ielgnaw
