### ISSUE TITLE
考虑将所有配置合并到 package.json

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#45]
目前 JSHint，JSCS 和 ESLint 都会自动读取 package.json 中相应的 xxxConfig 字段，避免项目内过多的 .xxxrc 配置文件。

大概流程为先从当前目录向上查找，以查找到第一个有 fecsConfig 字段的 package.json 为准，失败时则按现有流程读取 .fecsrc。

**Comment by otakustay** [comment]
在`edp jshint`时代，会从被检查文件所在目录开始逐级向上找，然后将N个`.jshintrc`给merge起来，而不是找到一个就停下

另外，要运行Home目录下的配置作为个人通用配置不

**Comment by chriswong** [comment]
现在找 .fecsrc 是会逐级 merge 的，但是我觉得 package.json 是指定一个模块，逐级 merge 的话会有问题，比如在 node_modules 下的模块（或者把 node_modules 当作停止查找的标记？）。或者可以加个标记要不要向上合并。

Home 下的配置如果考虑进来，不利于多人合作的项目吧，这个作 fecs 内置的就行是了。

**Comment by chriswong** [comment]
综合考虑 eagle 的问题，决定按以下流程实施：

1. 从当前目录向上检测 .fecsrc，存在则到 2，否则到 3。
2. 按旧流程，逐级查找 .fecsrc 并 merge。
3. 从当前目录向上检测 package.json，存在则后续以 package.json 中的 fecs 节点配置为准，否则仍按 2 处理。
