### ISSUE TITLE
ESLint 某些规则报错位置不准确的修正

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#46]
目前已知的规则有：

- [ ]  dot-notation （对应定位节点应为 node.property）
- [ ] space-infix-ops （对应定位节点应为 node.right/node.consequent/node.alternate）
- [ ] no-reserved-keys

需要做的步骤：

1. 修复后内置，增加 `fecs-` 前缀；
2. 去官方报 issues；
3. 为官方发 PR 或待官方修复发布后移除内置实现，移除配置中相应的 `fecs-` 前缀。

**Comment by zoumiaojiang** [comment]
添加一个触发的rule:
no-reserved-keys

**Comment by chriswong** [comment]
目前依赖的 **eslint** 版本为 `2.5.1`，该版本中，`dot-notation` 与 `space-infix-ops` 的 report 定位问题已经修复，`no-reserved-keys` 已经移除，被  `quote-props` 取代，而 `quote-props` 与 `fecs-properties-quote` 行为基本一致，所以在移除 `fecs-dot-notation`、 `fecs-space-infix-ops`、 `fecs-no-reserved-keys`，并替换  `fecs-properties-quote` 为  `quote-props` 后，issue 可关闭。
