### ISSUE TITLE
执行命令 fecs dirPath和 fecs ./dirPath 差异化好大

### ISSUE THREAD

**Issue by zoumiaojiang** [ecomfe/fecs#55]
执行命令 fecs dirPath和 fecs ./dirPath ，前者不能识别项目根目录下的.fecsignore和.fecsrc配置。但是后者能够识别。

**Comment by chriswong** [comment]
ignore 里是不是以 ./dirPaht 写的路径？

**Comment by chriswong** [comment]
这里是有个逻辑的，如果为 fecs 指定了path，会先判断 file.relative（不以 `./` 开头）是否是以 path 为前缀，如果是，则跳过 .fecsignore 的配置，不会被忽略。

当你以 ./ 开头指定 path 时，导致判断前缀的逻辑失败，所以会继续走 .fecsignore 的逻辑。

这里的目的是为了提高指定 path 的优先级，因为强制指定了检查，否则如果配置了忽略该目录，然后用 fecs 检查该目录时认为没有错误。
