### ISSUE TITLE
valid-jsdoc 对 @file 的检查问题

### ISSUE THREAD

**Issue by chriswong** [ecomfe/fecs#56]
1. 第一个注释块未必就会包含 `@file`，比如版权声明之类，有可能在第二个注释块
2. 在完全没有 `@file` 时，第一个注释块通常不会在文件头部，所以报错位置以第一个注释块为基准不合理

**Comment by otakustay** [comment]
版权声明是不是不应该用/** xxx的形式的jsdoc，而是/*! copyright呢？
我们应该是强制要求有@file的，所以自然放在第一个注释块？


Best regards

Gray Zhang



在 2015年1月21日 上午11:15:27, Chris (notifications@github.com) 写到:

第一个注释块未必就会包含 @file，比如版权声明之类，有可能在第二个注释块
在完全没有 @file 时，第一个注释块通常不会在文件头部，所以报错位置以第一个注释块为基准不合理

**Comment by chriswong** [comment]
> 版权声明是不是不应该用/** xxx的形式的jsdoc，而是/*! copyright呢？
> 我们应该是强制要求有@file的，所以自然放在第一个注释块？

这部分规范没作说明，所以需要作下兼容，我个人更偏向于版权和 `@file` 全到一块：

```
/**
 * Moye (Zhixin UI)
 * Copyright 2014 Baidu Inc. All rights reserved.
 *
 * @file 比 PC-UI WCal 好用的日历控件
 * @author chris(wfsr@foxmail.com)
 */
```

**Comment by otakustay** [comment]
同楼上，我也是这么写的，缺点是`/**`会被压缩掉，所以会在压缩后再写个脚本补回去……
