### ISSUE TITLE
Code Style Formatter将拼接的字符串压缩成一行

### ISSUE THREAD

**Issue by sleepholic** [ecomfe/fecs#62]
RT，代码中这种格式拼接的字符串
```
'<div>'+
    '<p></p>'+
'</div>'
```
会被压缩成
```
'<div>' + '<p></p>' + ' </div>'
```
从而导致单行字符数超长不能通过lint

辛苦处理一下~

**Comment by ishowshao** [comment]
好的，这是个比较棘手的问题，我处理一下

**Comment by ishowshao** [comment]
中间那行p的代码手工加的缩紧，格式化工具肯定是处理不了的，格式完了会变成行首对齐，对这个要有个心理准备

**Comment by otakustay** [comment]
其实我推荐这种代码就数组来拼HTML，这样format很容易处理……



Best regards

Gray Zhang



在 2015年2月4日 下午9:33:59, 邵帅 (notifications@github.com) 写到:

好的，这是个比较棘手的问题，我处理一下

**Comment by ishowshao** [comment]
写成数组

    [
        '<div>',
            '<p></p>',
        '</div>'
    ]

也还是会变成行首对齐，不过好处就是不用特殊处理了
😄

**Comment by sleepholic** [comment]
谢回复！所以现在的状态是至少不会被压成一行了是么？
用+是因为效率问题且写习惯了，不过代码量不会很多用数组倒没问题。
比较纠结就是缩进这个。。这里需要处理成行首对齐是因为“缩进只能四个空格”这条？对齐之后代码阅读起来略困难比较郁闷。。

**Comment by chriswong** [comment]
> 谢回复！所以现在的状态是至少不会被压成一行了是么？
> 用+是因为效率问题且写习惯了，不过代码量不会很多用数组倒没问题。
> 比较纠结就是缩进这个。。这里需要处理成行首对齐是因为“缩进只能四个空格”这条？对齐之后代码阅读起来略困难比较郁闷。。

数组内字符串的缩进已经处理了，允许前后 item 相差一个缩进
