### ISSUE TITLE
函数定义时分号的疑惑

### ISSUE THREAD

**Issue by helly** [ecomfe/fecs#63]
代码：
BccInstanceCreateView.prototype.updateByAccount = function(account) {
...
};

fecs检查报错：
fecs  INFO src\bcc\instance\CreateView.js (1 message)
fecs  WARN → line 312, col 6: Unexpected token ;

和规范里这条冲突了...
// 如果是函数表达式，分号是不允许省略的。
var funcName = function () {
};

**Comment by otakustay** [comment]
会不会报错的并不是这一行？能把整个文件提供一下么

**Comment by helly** [comment]
怎么单独给你附件合适？QQ邮箱回复好像不可以...

**Comment by otakustay** [comment]
如果不方便gist给的话，就直接邮箱附件给我，我的邮箱在个人资料里应该能看到吧，打成zip包就好



Best regards

Gray Zhang



在 2015年2月12日 下午3:12:40, helly (notifications@github.com) 写到:

怎么单独给你附件合适？QQ邮箱回复好像不可以...

**Comment by chriswong** [comment]
有下文了吗？

**Comment by otakustay** [comment]
没收到你的代码……或者你弄个gist？
