### ISSUE TITLE
less检查的一些问题

### ISSUE THREAD

**Issue by otakustay** [ecomfe/fecs#65]
试了下我项目里的，有不少问题，不知道是应该每个开一个issue还是集中在这里：

1. 不少报错无法定位行号，比如：

        ` When multiple selectors share a statement block, each selector statement must be per line

    目测是转义之类的出问题了

2. 对于`.less`也应用了“`@import`必须在最前”的规则，但这并不是必要的。我们的做法是引入一个库后，针对这个库设置一些变量，再引入下一个库，这使得一个库相关的逻辑在一起，个人认为比起把`@import`放一起有更好的维护性，如移除一个库的时候可以整段删代码
3. 对于`mixin`的检测要求所有`.less`维护自身的所有依赖。在实际中，项目可能只要一个`main.less`有完整的依赖关系即可，分开来的若干小的`.less`不需要一一写上`@import`。这个导致mixin和variable未定义的错误，我想是否可以忽略
4. 对于`When multiple selectors share a statement block, each selector statement must be per line`这个错误，我经常在文件中找不到错在哪里，没有多选择器（逗号分隔）占一行的情况

**Comment by Justineo** [comment]
2 这个问题估计是因为我在[这里](https://github.com/ecomfe/spec/blob/master/less-code-style.md#%E4%BB%A3%E7%A0%81%E7%BB%84%E7%BB%87)写了：

> 代码必须（MUST）按如下形式按顺序组织：
>
> `@import`
> 变量声明
> 样式声明

那看下这条是否也有必要修改一下。

3 这个问题我们这边其实也是由一个 `main.less` 去引入其他的片段编译，而不用每个 `.less` 文件可以单独编译。如果要忽略掉他们那得有一个方法来标识要检查的文件吧，还是想办法把不要的全都 ignore？

**Comment by otakustay** [comment]
@Justineo OK，我之前没仔细看理解成CSS的规范了……有规范的话严格按照规范执行，我来改代码

3这个问题在于，除了`main.less`外其它文件还是需要fecs检查的，只是应该忽略掉由于没有正确`@import`引起的问题，当然应该在`.fecsrc`中可以配置

**Comment by otakustay** [comment]
再来一个看不懂的：

```
fecs  WARN → line 12: `@gray-bg-color: #ebebeb;` Color definitions must use #RRGGBB format definition, Don't use RGB、HSL expression
```

**Comment by Justineo** [comment]
之前是 #RRGGBB 的，这个检查工具是那时候写的吧？后来 CSS 规范定的是小写，所以 Less 规范也升级过了。

**Comment by ielgnaw** [comment]
各位大神，现在 lesslint 有了一些更新，麻烦再看看上面这些问题是否还存在？

**Comment by otakustay** [comment]
新出来这么个问题：

```
fecs  INFO src/static/css/register.less (1 message)
fecs  WARN → line 246, col 1: `` Expected indentation of 0 spaces.
```

实际上这行是文件尾空行，啥也没有……

**Comment by ielgnaw** [comment]
@otakustay lesslint@0.1.17

**Comment by calent** [comment]
fecs支持sass lint吗？
