### ISSUE TITLE
disallow-overqualified-elements

### ISSUE THREAD

**Issue by copperybean** [ecomfe/fecs#73]
rule 013: [强制] 如无必要，不得为 `id`、`class` 选择器添加类型选择器进行限定。  (disallow-overqualified-elements)

这条规则限制为error太严格了，很多老的代码都是这么写的，修改代价太大。其实很多开源库的css也都这么写，建议改成warning吧

**Comment by chriswong** [comment]
规范不变，考虑实际情况，先降低为 warning，等 csshint 支持 inline comment rule 时恢复强制，由用户自己标识忽略。@ielgnaw

**Comment by DualWield** [comment]
建议改成warning + 1
