### ISSUE TITLE
fecs的文件配置的bug?

### ISSUE THREAD

**Issue by wzhscript** [ecomfe/fecs#75]
在一个单独文件中，我定义了一个类，供其他页面使用，如下所示:
``` javascript
var MyClass = (function(){...})();
```
我不想检查全局的unused vars，但想继续检查局部的unused vars，所以尝试了如下的文件级别配置，以避免MyClass 被识别成 unused vars (http://eslint.org/docs/rules/no-unused-vars.html)。
``` javascript
/*eslint no-unused-vars: [2, {"vars": "local", "args": "after-used"}]*/
var MyClass = (function(){...})();
```

可是这个配置貌似在fecs中不好使，MyClass仍然会被识别为unused vars。
但我发现在eslint自带的command-line工具中 (http://eslint.org/docs/user-guide/command-line-interface)却是可行的，能够正常识别上面的配置。

我现在用了一个替代方案（看起来比较捉急），如下：
``` javascript
/*eslint-disable no-unused-vars*/
var MyClass = (function(){
/*eslint-enable no-unused-vars*/
    ...
    ...
})();

```

请教各位大神，面对这个问题，如何更加优雅地配置？

**Comment by wzhscript** [comment]
继续尝试了配置到.fecsrc文件中，发现仍然不支持如下配置：
``` json
{
    "eslint": {
        "rules": {
            "no-unused-vars": [2, {"vars": "local", "args": "after-used"}],
            ...
        }
    }
}
```
disable配置在.fecsrc中也不行-_-||
``` json
{
    "eslint": {
        "rules": {
            "no-unused-vars": 0,
            ...
        }
    }
}
```

**Comment by chriswong** [comment]
我本地测试你的方法关掉 `no-unused-vars` 都没问题，你的 fecs 是什么版本？

默认的配置是：
> "no-unused-vars": [1, {"vars": "local", "args": "none"}]

发现的问题是 `vars: local` 同样会报文件内定义的全局变量，查了一下它的 `scope.type` 是 `function` 而不是 `global`。

**Comment by wzhscript** [comment]
我的版本是fecs 0.3.0-beta.1
我搞错了，在.fecsrc中确实是可以关掉no-unused-vars
但是如下配置还是会提示"[建议] 可能会导致代码质量下降的问题。（MyClass is defined but never used）"
```json
"no-unused-vars": [1, {"vars": "local", "args": "none"}]
```
根据官方的[解释](http://eslint.org/docs/rules/no-unused-vars.html)，上面的配置不应该提示全局变量MyClass。
而eslint官方的[command-line](http://eslint.org/docs/user-guide/command-line-interface)确实是这样实现的，没有问题。

**Comment by chriswong** [comment]
是因为默认打开了 env node，你配置中把它关了就行

**Comment by wzhscript** [comment]
原来如此，问题解决了哈，非常感谢:D
