### ISSUE TITLE
基于fecs的git pre-commit hook

### ISSUE THREAD

**Issue by cxtom** [ecomfe/fecs#82]
基于fecs的git pre-commit hook，可以实现在代码提交之前自动运行fecs，对提交的文件进行检查，如果不符合规范则会阻止提交，地址是：
https://github.com/cxtom/fecs-git-hooks
还有待改进，欢迎一起交流

**Comment by otakustay** [comment]
@yanghuabei 你把这个和我们的对一下，看是不是能相互借鉴
