### ISSUE TITLE
es6 set 误报

### ISSUE THREAD

**Issue by Neverland** [ecomfe/fecs#89]
set a(val) {
        this.set('a', val);
}

prepare() {
        a = 1;
}

fecs  "a" is not defined.

**Comment by chriswong** [comment]
fecs 什么版本？

**Comment by Neverland** [comment]
fecs 0.3.8-beta.6

**Comment by otakustay** [comment]
这个代码看不大懂……确定`prepare`里应该是`a = 1`而不是`this.a = 1`？因为不在`class`或`object`里去声明`set a(val) {}`应该是语法不通的……

**Comment by chriswong** [comment]
@Neverland 给个完整的代码吧
