### ISSUE TITLE
能否忽略 *.mockup.js

### ISSUE THREAD

**Issue by Justineo** [ecomfe/fecs#90]
现在已有可以忽略压缩文件（`*.min.js` 等）和模板文件（`*.tpl.html`），可否增加一种 `*.mockup.js`（或者也有人用 `*.mock.js`）。有的老项目还定期有更新，里面的 mockup 内容不是放在单独的 `mockup` 目录下面的。

**Comment by Justineo** [comment]
补充一下，主要还是由于 `.fecsignore` 文件在 eagle 不生效。

**Comment by 599316527** [comment]
我們有 `*.config.js` 也是 mockup 數據，也需要忽略

**Comment by otakustay** [comment]
- 从道理上来说，我们不应该忽略`.tpl.html`，而应该仅仅是把`doctype`的检测规则给去除
- `.min.js`是机器生成的，我们自然不检查

所以综合上面，我们的原则应该是：

1. 不适用的规则自动禁用
2. 非人写的代码不检查

如果`.mockup.js`不是人手写的，那么我赞同忽略，反之如果还是人写出来的，我认为无论是什么代码，只要你手指敲着键盘，就应该符合我们的规范，`.config.js`同理

**Comment by otakustay** [comment]
我觉得我们直接禁掉了对`.tpl.html`的检查纯粹是技术做不好的原因，不是真的想给禁掉

**Comment by Justineo** [comment]
我们的投放端里面有后端通过全局变量提供数据的逻辑，mockup 就是模拟一个全局变量，但这样会触发定义但未使用这种规则。如果不能全局忽略的话，我们目前也只能每个文件去批量加上注释禁用这条规则了……

**Comment by Justineo** [comment]
@otakustay 道理的确如你所说。

**Comment by otakustay** [comment]
所以其实应该按文件名匹配去掉`no-undef`这个规则

@chriswong 我们以前说在`package.json`中放fecs规则让eagle平台识别这事怎么样了来着

**Comment by chriswong** [comment]
上个版本就已经支持 package.json 了，不过每次提交还是需要让它有 diff。

固定 .fecsrc 支持的事，EE 还没时间开发...

**Comment by otakustay** [comment]
那我觉得可以这样，对以下类型的文件：

1. mockup
2. 配置
3. 测试

去除`no-undef`这个规则的检查，因为这些文件是非常容易出现各种全局变量的，切全局变量也是合理的，我们也就不再需要特别为`jasmine`啊`mocha`啊各种框架来设`globals`了

**Comment by chriswong** [comment]
测试的文件本身是有 env 直接支持配置的，内置就配了 jasmine。

mockup 能不能集中在 mockup 目录?

配置文件这个太泛了，只能自己指定

**Comment by 599316527** [comment]
`.fecsignore` 已经支持了？
http://ecmb.bdimg.com/adtest/d68460fc0eb18b68253c8f353a2ac5cb.txt

**Comment by chriswong** [comment]
> 有的老项目还定期有更新，里面的 mockup 内容不是放在单独的 mockup 目录下面的。

可以支持

> 我觉得我们直接禁掉了对.tpl.html的检查纯粹是技术做不好的原因，不是真的想给禁掉

主要是因为模板中 if else 导致多个重复 id，属性中输出变量或表达式包含的字符等，不只是 doctype 的问题

> .fecsignore 已经支持了？

本地一直支持，只不过 eagle (cooder) 上不支持而已

**Comment by Justineo** [comment]
赞 :+1:
