### ISSUE TITLE
fecs 误报

### ISSUE THREAD

**Issue by blessbygod** [ecomfe/fecs#95]
1、 requirejs   require([ "a",
                                      "b",
                                      "c",
                                       ..., 
                                       "n"],

被误报多个参数，（fecs规定最多6个）

2、 backbone, events     用的函数名称 _click_toggleClass, 这种便于分辨事件和内部函数的命名， 被报违反驼峰写法，能不能对这种的自定义或者宽容一些。

**Comment by Justineo** [comment]
这个我理解不能叫误报吧。误报应该是指符合我们的编码规范但是 fecs 报了错。要有例外的情况应该自己去用修改配置的方式去处理，方法在这个 repo 的 wiki 里都有。

**Comment by blessbygod** [comment]
@Justineo 

    确实不能叫误报 ：），  我担心的是我修改了自己的配置会不会因为和公共配置不一致导致代码提交不通过， 最近不是开始推规范了。。。。。

**Comment by blessbygod** [comment]
@Justineo 

   requirejs那个确实是误报，   比如规范尽量让写就近依赖的写法。 虽然我写的数组，但确实报的 参数不能多于6个， 而我实际的参数就两个，一个是依赖数组，一个是回调函数

**Comment by chriswong** [comment]
第一个报的应该是回调函数的参数
