### ISSUE TITLE
no-global-require 误报

### ISSUE THREAD

**Issue by otakustay** [ecomfe/fecs#96]
RT，global require用于异步加载某些模块是必然会使用的

**Comment by chriswong** [comment]
不是取消，如 @errorrik 解释，

> [强制] 模块定义中只允许使用 `local require`，不允许使用 `global require`。

规范的目的是避免 AMD factory 中没有 `require` 这个 param 时，在 factory 内使用的 `require` 会变成 `global require`。

当然规范的话术会导致理解歧义，我作了一些补充，默认的信息是：

> Expected a local require (Missing `require` in AMD factory).

使用 `--reporter baidu` 时：

> [强制] 模块定义中只允许使用 `local require`，不允许使用 `global require`（AMD factory 中漏写了 `require` 参数所致）。
