### ISSUE TITLE
for 语句误报

### ISSUE THREAD

**Issue by lzfee0227** [ecomfe/fecs#98]
for 的 final-expression 为空的时候
```for (var i = 10; i--;) {}``` 报 ```Missing whitespace after semicolon```
```for (var i = 10; i--; ) {}``` 报 ```There should be no spaces inside this paren```
```0.4.0-beta.1``` 无此问题
```0.4.0``` 有此问题
是修复这个 issue #94 ```for中的3个分号后空格没检查 ``` 引起的？

**Comment by 599316527** [comment]
+1
